apply plugin: 'com.android.application'

android {
    namespace 'com.jazzcrab.jazznote'
    compileSdk 34

    defaultConfig {
        applicationId "com.jazzcrab.jazznote"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('../jazznote-release.keystore')
            storePassword 'rentgen123'
            keyAlias 'jazznote'
            keyPassword 'rentgen123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.8.0'
}
